http:
  host: 'localhost'
  port: 3333

database:
  host: 'localhost'
  port: 5432
  databaseName: 'basic-auth'
  username: 'postgres'
  password: 'example'

auth:
  jwt:
    secret: 'you have to change this secret'
    expiresIn: '1d'
